### ISSUE TITLE
yarn tsc error when bumping backstage to 1.32.1

### ISSUE THREAD

**Issue by nia-potato** [dweber019/backstage-plugins#76]
Hi @dweber019  thanks for the great plugin! 

btw I am getting this error when running yarn tsc 

```
packages/app/src/App.tsx:147:3 - error TS2322: Type '(Partial<import("/var/gitlabrunner/buildbot/workspace/builds/z3Qtt7Xp/0/corp/backstage/src/node_modules/@dweber019/backstage-plugin-simple-icons/node_modules/@backstage/core-app-api/dist/index").AppIcons> & { ...; }) | undefined' is not assignable to type '(Partial<import("/var/gitlabrunner/buildbot/workspace/builds/z3Qtt7Xp/0/corp/backstage/src/node_modules/@backstage/core-app-api/dist/index").AppIcons> & { ...; }) | undefined'.
  Type 'Partial<AppIcons> & { [x: string]: IconComponent; }' is not assignable to type '(Partial<AppIcons> & { [x: string]: IconComponent; }) | undefined'.
147   icons: simpleIconsColor,
```

is this expected?

**Comment by dweber019** [comment]
I don't think so, at least I don't get the error in this repo.

**Comment by dweber019** [comment]
Having a hard time to reproduce this but changed to a simpler type definition in https://github.com/dweber019/backstage-plugins/pull/78

**Comment by dweber019** [comment]
@mattthym are you sure your on the latest update with all changes from the upstream backstage project as I can see differences in the yarn scripts like https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/package.json.hbs#L9

**Comment by mattthym** [comment]
Thanks for fixing, @dweber019! :bouquet:
